import React, { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { localDb } from '../lib/localDb';
import { Button, Card, Label } from './ui';
import { FileCode, Download, Copy, RefreshCw, CheckCircle } from 'lucide-react';

export const XMLFeedsPanel = () => {
    const [googleXml, setGoogleXml] = useState<string>('');
    const [pinterestXml, setPinterestXml] = useState<string>('');
    const [loading, setLoading] = useState(false);
    const [copied, setCopied] = useState<string | null>(null);

    useEffect(() => {
        loadFeeds();
    }, []);

    const loadFeeds = () => {
        const g = localDb.getFeedSnapshot('google');
        const p = localDb.getFeedSnapshot('pinterest');
        if (g) setGoogleXml(g);
        if (p) setPinterestXml(p);
    };

    const handleRegenerate = async () => {
        setLoading(true);
        const g = await api.feeds.generateGoogleShoppingXML();
        const p = await api.feeds.generatePinterestXML();
        setGoogleXml(g);
        setPinterestXml(p);
        setLoading(false);
        alert('Feeds regenerated successfully.');
    };

    const copyToClipboard = (text: string, type: string) => {
        navigator.clipboard.writeText(text);
        setCopied(type);
        setTimeout(() => setCopied(null), 2000);
    };

    const downloadFeed = (xml: string, filename: string) => {
        const blob = new Blob([xml], {type: 'text/xml'});
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
    };

    const FeedCard = ({ title, type, xml, iconColor, filename }: { title: string, type: string, xml: string, iconColor: string, filename: string }) => (
        <Card className="h-full flex flex-col">
            <div className="flex items-center gap-3 mb-4">
                <div className={`p-3 rounded ${iconColor} bg-opacity-20`}>
                    <FileCode className={`w-6 h-6 ${iconColor.replace('bg-', 'text-')}`} />
                </div>
                <div>
                    <h3 className="text-white font-medium">{title}</h3>
                    <p className="text-sm text-gray-500">
                        {xml ? `${(xml.length / 1024).toFixed(2)} KB • Cached` : 'Not Generated'}
                    </p>
                </div>
            </div>

            <div className="flex-1 mb-4">
                <Label>Preview (First 500 chars)</Label>
                <div className="bg-charcoal-lighter border border-charcoal-light rounded p-3 text-xs font-mono text-gray-400 h-32 overflow-hidden relative">
                    {xml ? xml.slice(0, 500) + '...' : 'No data. Click Regenerate.'}
                    <div className="absolute inset-x-0 bottom-0 h-12 bg-gradient-to-t from-charcoal-lighter to-transparent"></div>
                </div>
            </div>

            <div className="space-y-3 mt-auto">
                 <div className="flex items-center gap-2 text-xs text-gray-500 bg-charcoal p-2 rounded border border-charcoal-lighter break-all">
                    <span className="font-semibold text-gray-400">URL:</span>
                    https://www.aureusgoldcorp.com/feeds/{type}.xml
                 </div>
                 <div className="flex gap-2">
                    <Button variant="outline" className="flex-1" onClick={() => copyToClipboard(xml, type)} disabled={!xml}>
                        {copied === type ? <CheckCircle className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />} 
                        {copied === type ? 'Copied' : 'Copy'}
                    </Button>
                    <Button variant="secondary" className="flex-1" onClick={() => downloadFeed(xml, filename)} disabled={!xml}>
                        <Download className="w-4 h-4 mr-2" /> Download
                    </Button>
                 </div>
            </div>
        </Card>
    );

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center bg-charcoal-light p-4 rounded border border-charcoal-lighter">
                <div>
                    <h3 className="text-white font-medium">Feed Status</h3>
                    <p className="text-sm text-gray-500">Feeds are automatically regenerated by the system cron.</p>
                </div>
                <Button onClick={handleRegenerate} isLoading={loading}>
                    <RefreshCw className="w-4 h-4 mr-2" /> Regenerate Now
                </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FeedCard 
                    title="Google Shopping" 
                    type="google" 
                    xml={googleXml} 
                    iconColor="text-blue-400 bg-blue-900" 
                    filename="google_shopping_feed.xml"
                />
                <FeedCard 
                    title="Pinterest Catalog" 
                    type="pinterest" 
                    xml={pinterestXml} 
                    iconColor="text-red-400 bg-red-900" 
                    filename="pinterest_catalog.xml"
                />
            </div>
        </div>
    );
};